---
- hosts: 172.31.29.217
  become: yes
  tasks:
  - include_tasks : Myfilehandler.yml
  - name: I want to create a directory
    file:
     path: /home/ubuntu/MyNewDirectory
     state: directory
  - name: I want to copy the text from master to my new file on node side
    copy:
      src: textfile.txt
      dest: /home/ubuntu/MyCopiedTxtFile
  - name: I want to install apache2 webserver
    apt:
      name: apache2
      state: present

  - name: I want to copy dynamic files into node side
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
        